README.md
Github generates copy link to heading buttons for all <hX> elements. We dont want those in the heading.
=> Dont use h tags in the heading README.md

build/package/goreleaser/goreleaser.yml
Because the rig cli is it's own go module, we need to change directory
before we build the binary.
=> :bug: fix goreleaser build of rig cli

deploy/charts/rig/Chart.yaml, deploy/charts/rig/templates/ingress.yaml, deploy/charts/rig/templates/service.yaml
Kubernetes service discovery creates an environment variable called
`<service-name>-PORT` for each service in the namespace where a pod
runs. The main service in the chart used the fullname helper as name.
When using rig as release name this resulted in the service being called
`rig`. This then means that each pod in the namespace would get an
environment variable called `RIG_PORT`. This clashes with the
environment override of `port` in the rig config.
This fix changes the service name by adding `-svc` as suffix. The
service discovery variable will hence be `RIG_SVC_PORT` and no longer
cause a clash.
=> 🐛 Fix clash between k8s svc discovery and rig env var

cmd/rig/cmd/auth/get.go, cmd/rig/cmd/auth/get_auth_config.go, cmd/rig/cmd/auth/login.go, cmd/rig/cmd/auth/setup.go, cmd/rig/cmd/base/auth.go, cmd/rig/cmd/base/client.go, cmd/rig/cmd/base/register.go, cmd/rig/cmd/capsule/create.go, cmd/rig/cmd/capsule/create_build.go, cmd/rig/cmd/capsule/push.go, cmd/rig/cmd/cmd_config/config.go, cmd/rig/cmd/cmd_config/context.go, cmd/rig/cmd/config/init.go, cmd/rig/cmd/config/use_context.go, cmd/rig/cmd/project/create.go, cmd/rig/cmd/project/list.go, cmd/rig/cmd/project/setup.go, cmd/rig/cmd/project/use_project.go
Added support for automatic prompting for login and selection 
of project. To omit the checks, add a base.OmitProject / 
base.OmitUser to the annotations of the cmd.
I have changed a bit in the contexts, so it is needed to remove 
the config.yaml file. Dunno where on linux or windows, but in 
mac the file is at:
Library/Application Support/rig/config.yaml
=> CMD Prompt for login & project use

Makefile, cmd/rig-server/root.go, cmd/rig/cmd/capsule/create_build.go, cmd/rig/cmd/capsule/setup.go, deploy/charts/rig/templates/_config.tpl, deploy/kind/create.sh, deploy/registry/registry.yaml, internal/config/types.go, internal/service/capsule/build.go, internal/service/capsule/service.go
Also added new configuration necessary to interface with the developer
docker registry
=> Automatically add a developer registry to the kind cluster when using 'Make kind-create'

Makefile, deploy/charts/rig/templates/certmanager.yaml, deploy/charts/rig/templates/crd-capsules.yaml, deploy/charts/rig/templates/deployment.yaml, deploy/charts/rig/templates/service.yaml, deploy/charts/rig/templates/webhookconfiguration.yaml, deploy/charts/rig/values.yaml, deploy/kind/create.sh, internal/config/defaults.go, internal/config/types.go, internal/service/operator/operator.go, test/integration/controller/capsule_controller_test.go
- Add `webhooks.enabled` value in chart and configure webhook related
resources based on this.
- Add CRD to chart
- Improve `deploy/kind/create.sh`: Add commands which installs docker registry,
cert-manager and metrics-server in the cluster.
- Add rig config for kubernetes client, so that we can toggle wether or
not to run webhooks
=> ✨ Add CRD webhook support 

cmd/rig/cmd/capsule/create_build.go, cmd/rig/cmd/capsule/deploy.go, cmd/rig/cmd/capsule/setup.go
The flag specifies if an image should not be searched for locally.
Sometimes you have a remote image also pulled locally. In that case,
you might not want to refer to the local one (which using a dev-registry
would unnecessarily be pushed into the dev-reg if considered a local image).
=> CLI: Add --remote flag to create-build and deploy

build/package/goreleaser/Dockerfile.core, build/package/goreleaser/goreleaser.yml, cmd/rig-operator/main.go
- add version command for rig-operator
=> 📦️ Add goreleaser files for rig-operator

.gitignore, Makefile
As the rig-operator by default gets installed from the rig-platform
chart, make kind-deploy failed if the operator was already installed
as a standalone release.
This ensures that the two are installed as separate releases so that the
make targets work across the rig and the platform repositories.
=> 🐛 Fix make chart deployment

Makefile
`rig-operator.enabled` does not exist any more and is hence not needed.
=> 🔨 Refactor deploy make targets

cmd/rig/cmd/dev/kind/create.go, deploy/charts/rig-platform/Chart.yaml, deploy/charts/rig-platform/templates/NOTES.txt, deploy/charts/rig-platform/values.yaml
We cannot depend on the rig-operator CRDs in the rig-platform chart by
having rig-operator as a helm dependency. The chart *needs* to be
installed before the CRDs are used.
This removes the option of installing rig-operator as a part of the
rig-platform chart.
Update NOTES.txt with proper URLs.
=> ➖ Remove rig-operator as a dependency of rig-platform

deploy/charts/rig-operator/templates/clusterrole.yaml, pkg/controller/capsule_controller.go, test/integration/k8s/capsule_controller_test.go, test/integration/k8s/capsule_validation_test.go, test/integration/k8s/setup_test.go
The operator now watches configmaps and secrets for changes in order to
determine wether we need to reconcile a capsule.
Eg. when we depend on a secret or a configmap for environment variables
or configfiles, we want to update an annotation on the deployment when
these change so that we roll the deployment.
- ✨ Introduce a hash function which we use for calculating a hash of the
current configuration eg. contents of configmaps and secrets we depend
upon.
- 🐛 Fix a few bugs in `upsertIfNewer`
- ✅ Disable validation integration test tracked in https://github.com/rigdev/rig/issues/226
- 🔊 Improve logging
=> ✨ Watch for config changes

pkg/controller/capsule_controller.go
This makes the operator watch changes to owned `Deployment`, `Service`,
`Ingress`, `HorizontalPodAutoscaler` and `Certificate` resources. This
ensures that if a resources is missing for some reason, then we recreate
it.
=> ✨ Recreate missing resources

test/integration/k8s/capsule_controller_test.go, test/integration/k8s/capsule_validation_test.go, test/integration/k8s/setup_test.go
There has been issues with running multiple instances of envtest in
parallel. This changes the tests to use a single instance of envtest by
using a testify test suite and its `SetupSuite` and `TearDownSuite` to
setup and teardown envtest.
fixes #226
=> ✅ Use one instance of envtest across tests

pkg/controller/capsule_controller.go, pkg/hash/hash.go, pkg/hash/hash_test.go, test/integration/k8s/capsule_controller_test.go, test/integration/k8s/capsule_validation_test.go, test/integration/k8s/suite_test.go
Adds a new feature where namespace scoped environment variables can
be added by annotating a secret or configmap with rig.dev/shared-config.
Introduce `pkg/hash` for calculating checksums of configmaps and
secrets.
=> ✨ Support namespace scoped shared config 

.github/workflows/stale.yml
After 30 days of inactivity we will mark stale and after 7 days the
issue or PR will be closed.
For issues, we will only check for staleness for issues with the
needs-more-info label.
=> 👷 Add stale workflow

deploy/charts/rig-operator/templates/deployment.yaml, pkg/manager/manager.go
Leader election namespace was hardcoded to "rig-system". When deploying
in other namespaces the granted role didnt allow for access to leases in
rig-system but instead in the namespace where it was deployed.
This change uses the downward API to make an environment variable
available in the pod for what namespace we are running in. This can then
be used to ensure that we use lease resources in the same namespace as
where the operator is running.
fixes #267
=> :bug: Ensure leader election uses same namespace as operator

pkg/controller/capsule_controller.go
If a Capsule references a Secret *and* a ConfigMap sharing the same
name, we are generating a deployment with name clashes in the list of
volumes.
This fixes the generated volume names, by changing their prefix to be
either configmap or secret instead of volume.
=> :bug: Ensure configmap and secret volume names dont overlap

Makefile, docs/crd-ref-docs/config.yaml, docs/crd-ref-docs/v1alpha2-config.yaml, docs/docs/api.mdx, docs/docs/api/config/v1alpha1.md, docs/docs/api/v1alpha1.md, docs/docs/api/v1alpha2.md, docs/menu.js, docs/src/css/custom.css, pkg/api/config/v1alpha1/groupversion_info.go, tools/go.mod, tools/go.sum, tools/tools.go
Add automated API resource documentation. We use the crd-ref-gen project
to generate markdown based on the kubernetes resource types.
- ensure make gen generates docs
- remove kuberbuilder:skip from config api group and instead ensure that
the maketarget only generates for our main api group.
=> :memo: Add resource API documentation

.github/workflows/test.yml, Makefile, docs/docs/api/v1alpha2.md, go.mod, go.sum
- Add check to ensure that all generated files are committed. This
includes checking that the go modules are tidied using `go mod tidy`.
Fixes https://github.com/rigdev/rig/issues/322
- Create ci make targe
- Ensure all test jobs use the ci make target in order to share
the same cache of installed tools, go packages and go build cache.
- Use go version from go.mod
=> 👷 CI test improvements 

pkg/controller/capsule_controller.go
For some reason we didn't pass Command or Args to the underlying
Deployment resource, which means that we always would run the entrypoint
of the docker container instead of what was set in Command or Args.
=> :bug: Ensure that command and args are set

deploy/charts/rig-operator/Chart.yaml, deploy/charts/rig-operator/templates/crd.yaml, docs/docs/api/v1alpha2.md, pkg/api/v1alpha2/capsule_types.go, pkg/controller/capsule_controller.go, test/integration/k8s/capsule_controller_test.go
This enables matching requests against a path prefix, which will be
required in order to hit the ingress.
=> ✨ Add pathPrefix option for ingress interface

cmd/rig/cmd/capsule/mount/remove.go, cmd/rig/cmd/capsule/mount/set.go
The CLI now prompts you to select a path from the existing files when
removing.
=> :children_crossing: Make it easier to remove mounted files from the CLI

cmd/rig/cmd/capsule/common.go, cmd/rig/cmd/capsule/root/get.go
After the environment change, we need to fetch rollouts for a capsule
differently.
=> :bug: Fix CLI bug with printing capsules

cmd/rig/cmd/base/common.go, cmd/rig/cmd/base/register.go, cmd/rig/cmd/config/init.go, cmd/rig/cmd/config/setup.go
If you had no context, it would prompt to make a context twice.
=> :bug: Fix CLI bug with 'rig config init'

cmd/rig/cmd/base/auth.go, cmd/rig/cmd/base/register.go, cmd/rig/cmd/cmdconfig/config.go, cmd/rig/cmd/cmdconfig/context.go, cmd/rig/cmd/config/init.go, cmd/rig/cmd/config/use_context.go
If the current Rig context referenced a user which no longer existed, the CLI
would fail with an unhelpful error message.
We now inform that the context is probably broken and prompt for rebuilding
it.
=> :bug: Fix CLI bug where it couldn't start if the context had an unknown user

docs/docs/api/platform-api.md, proto/rig/api/v1/capsule/service.proto
The endpoint returns values for each instance of the capsule. Thus if you
use a pagination with a fixed limit, the time window of the metrics
depends on the number of instances the capsule has.
=> :boom: Change CapsuleMetrics to accept a timestamp instead of pagination

pkg/manager/manager.go
Sometimes when scripting quick installation of the rig-operator and
resources depending on the Capsule API, you would get an error because
the validation webhooks were not ready yet.
Including the webhooks' ready state in the healthcheck enables us to
`helm install --wait` which will block until the healthchecks passes.
=> 🩺 Add health check for webhooks

pkg/controller/cron_jobs_step.go, pkg/controller/deployment_step.go, pkg/controller/network_step.go, pkg/controller/pipeline/capsule_request.go, pkg/controller/pipeline/pipeline.go, pkg/controller/plugin/objectTemplate/main.go, pkg/controller/plugin/objectTemplate/plugin_test.go, pkg/controller/service_account_step.go, pkg/controller/service_monitor_step.go, pkg/controller/vpa_step.go, pkg/obj/merge.go, pkg/obj/merge_test.go, pkg/service/config/config.go, pkg/service/config/config_test.go, test/integration/k8s/capsule_controller_test.go, test/integration/k8s/suite_test.go
We now properly handle merging of child lists which contain a 'mergeKey'
Essentially, we just make sure to adhere to JSON Merge Path (https://datatracker.ietf.org/doc/html/rfc7386)
=> :bug: Fix merging of runtime.Object

pkg/controller/plugin/annotations/main.go, pkg/controller/plugin/annotations/plugin_test.go, pkg/controller/plugin/datadog/main.go, pkg/controller/plugin/datadog/plugin_test.go, pkg/controller/plugin/helpers.go, pkg/controller/plugin/objectTemplate/main.go, pkg/controller/plugin/objectTemplate/plugin_test.go, pkg/controller/plugin/sidecar/main.go
Part of the refactor is to also handle cases where we need to
do templating in a series of steps. E.g. objectTemplate can use
capsule and currentObject as template values, if the name of currentObject
is templated on the capsule, then you first need to template the config
using the capsule, then fetch the currentObject, then template again.
=> :recycle: Refactored how we handle templating in plugins

cmd/rig-operator/apichecker/apichecker.go, deploy/charts/rig-operator/templates/_helpers.tpl, deploy/charts/rig-operator/templates/apicheck/job.yaml, deploy/charts/rig-operator/templates/apicheck/rbac.yaml, deploy/charts/rig-operator/templates/apicheck/serviceaccount.yaml, deploy/charts/rig-operator/values.yaml
This adds a post-install helm hook which will block the helm install
until the webhooks are reachable from the api server.
=> ✨ Add apicheck post-install helm hook

cmd/rig-operator/certgen/create.go, cmd/rig-operator/certgen/k8s.go, cmd/rig-operator/certgen/patch.go, deploy/charts/rig-operator/templates/_helpers.tpl, deploy/charts/rig-operator/templates/apicheck/rbac.yaml, deploy/charts/rig-operator/templates/apicheck/serviceaccount.yaml, deploy/charts/rig-operator/templates/certgen/create-job.yaml, deploy/charts/rig-operator/templates/certgen/patch-job.yaml, deploy/charts/rig-operator/templates/certgen/rbac.yaml, deploy/charts/rig-operator/templates/certgen/serviceaccount.yaml, deploy/charts/rig-operator/templates/certificate.yaml, deploy/charts/rig-operator/templates/crd.yaml, deploy/charts/rig-operator/templates/webhookconfiguration.yaml, deploy/charts/rig-operator/values.yaml, pkg/controller/capsule_controller.go
- 🐛 certgen: Fix missing time on issued certificate.
- ♻️ certgen: make generated certificate comply with the
kubernetes.io/tls secret type.
- 🚚 certgen: rename `patch-webhook-config` to just be `patch`
- ✨ chart rig-operator: add certgen job for when cert-manager is
disabled.
- 🐛 rig-operator: could not start when cert-manager CRDs weren't
installed.
=> ✨ Make optional cert-manager in helmchart

build/package/goreleaser/goreleaser.yml, build/package/goreleaser/rig.Dockerfile, taskfile.yaml
This adds goreleaser configuration for publishing the `rig` CLI as a
docker image.
=> ✨ Publish rig CLI as docker image

build/package/goreleaser/Dockerfile, build/package/goreleaser/goreleaser.yml
- Rename of google_sql_proxy -> google_cloud_sql_auth_proxy
- Fix release of rig-ops binary: missing archive generation
=> 🐛 Fix goreleaser config

build/package/goreleaser/rig.Dockerfile
Previously we did a staged docker build which resulted in the home
directory for the nonroot user not existing.
=> 🐛 Ensure we have a homedir for rig CLI

pkg/controller/capsule_controller.go, pkg/controller/deployment_step_test.go, pkg/controller/pipeline/capsule_request.go, pkg/controller/pipeline/capsule_request_test.go, pkg/controller/pipeline/pipeline.go, pkg/controller/pipeline/request.go, pkg/controller/pipeline/step.go, pkg/service/pipeline/service.go, plugins/annotations/plugin_test.go, plugins/datadog/plugin_test.go, plugins/google_cloud_sql_auth_proxy/plugin_test.go, plugins/object_template/plugin_test.go, plugins/placement/plugin_test.go
We want to reuse the commit-logic from the capsule request for the
project CRD. The abstraction extracted is not the nicest, but it'll
do for now.
=> :recycle: Refactor capsule request to be ready for a project reconciler

.github/workflows/pr-update-docs.yml
Dependabot does not have access to secrets, so no reason to try to
deploy these PRs.
=> :bug: Skip PR deploy for dependabot PRs

cmd/rig-ops/cmd/plugins/setup.go
We will be renaming plugins to mods soon. This is a small first step
which simply makes `mods` be an alias of plugins in the `rig-ops` CLI.
This will be featured on the new website content we are working on.
=> 🚚 Add alias for `rig-ops plugins list`

docs/docs/api/platform-api.md, proto/rig/api/v1/capsule/change.proto, proto/rig/api/v1/capsule/rollout.proto, proto/rig/api/v1/capsule/service.proto, proto/rig/api/v1/project/service.proto, proto/rig/model/metrics.proto, proto/rig/model/revision.proto
Also had to move some metric messages in to `models` as they introduced
circular dependencies. Project cannot depend on Capsule at this point.
=> :sparkles: Capsule service updates for source-of-truth revision stuff

docs/docs/api/platform-api.md, go.mod, go.sum, proto/rig/api/v1/capsule/service.proto
**PromotionV1 Proposal:**
- A Simple “GetEnvironmentDifferences” endpoint, that computes the difference between two specs.
- Can be used to promote with a subsequent deploy of changes -+ changes.
- In the dashboard, we get the differences and open the configuration modal.
=> :sparkles: Endpoint to get the difference between to environments in terms of changes

plugins/capsulesteps/deployment/watcher.go
It turns out ImageID is the canonizal digested image path, where Image is some internal product (just a SHA when digests are used).
=> 🐛 Fix reading of instance image ID (ImageID in favor of Image)

docs/docs/api/config/v1alpha1.md, docs/docs/operator-manual/gitops.mdx, pkg/api/config/v1alpha1/platform_config_types.go, pkg/api/config/v1alpha1/platform_config_validate.go, pkg/api/config/v1alpha1/platform_test.go, pkg/api/config/v1alpha1/zz_generated.deepcopy.go, pkg/service/config/config_test.go
The previous format was not mergeable by Strategic Patch Merge
which is an issue if you use e.g. secrets to inject configuration into
the platform.
=> ✨ Change platform config format for Git clients
