rigdev/rig

README.md
proto/rig/buf.md
proto/rig/buf.yaml

- buf.md and yaml
- twitter rig_dev link
- buf md
- buf.md

Buf readme

---

cmd/rig/cmd/storage/common.go
cmd/rig/cmd/storage/copy.go
cmd/rig/cmd/storage/delete_object.go
cmd/rig/cmd/storage/get_object.go
cmd/rig/cmd/storage/ls.go

- ns --> rs
- ns to rs
- rs --> rig

ns to rig in storage

---

deploy/charts/rig/Chart.yaml
deploy/charts/rig/templates/mongodb/statefulset.yaml

- ⬆️ Update appVersion to v1.0.0
- 🐛 fix what helper we use for volume claim template labels. We can't
use one that changes because it's immutable.

🔖 chart: Release v0.4.0

---

cmd/rig-admin/cmd/root.go
cmd/rig-admin/cmd/users.go
cmd/rig/cmd/user/create.go
cmd/rig/cmd/utils/useridentifier.go
cmd/rig/cmd/utils/utils.go
internal/service/user/service.go

It existed in both 'rig' and 'rig-admin' with two
different implementations

Refactor duplicated Create User commands

---

.github/workflows/semantic-tags.yml

This contains various fixes for the dashboard.
- making sure validation is in check + fixed height on toast
- bumped SDK version + implemented "verify" logic for when creating new builds.
- fixed link
- Fix the last few Lorem ipsum text fields

⬆️ Bump dashboard to v0.2.9

---

cmd/rig/cmd/capsule/create.go

- added cmd to capsule create
- cmd and args
- capsule create environment variables

cmd, args and envs in capsule create

---

.github/ISSUE_TEMPLATE/bug_report.md

🚸 Improve bug report template

---

.github/workflows/pr.yml
Makefile

This will run all tests including integration tests in CI.

✅ Run integration tests in CI

---

.vscode/settings.json
internal/handler/api/capsule/deploy.go
internal/service/capsule/rollout.go
internal/service/capsule/service.go
proto/rig/api/v1/capsule/rollout.proto

remove prerun from capsule cmd

improved capsule deploy flow + author and updated at on cofig files

---

cmd/common/prompt.go
cmd/rig-admin/cmd/capsule.go
cmd/rig/cmd/capsule/common.go
cmd/rig/cmd/capsule/create.go
cmd/rig/cmd/capsule/deploy.go
cmd/rig/cmd/storage/setup.go
go.mod
go.sum

- improved capsule deploy flow + author and updated at on cofig files
- improved capsule deploy flow + author and updated at on cofig files
- rebase

Second half of #99

---

cmd/common/prompt.go
cmd/common/utils.go
cmd/common/utils_test.go
cmd/rig/cmd/capsule/deploy.go
cmd/rig/cmd/capsule/list_builds.go

Also improving formatting of build/image prompt selection lists

Format image/build timestamps differently

---

test/integration/k8s/capsule_controller_test.go
test/integration/k8s/setup_test.go

✅ Fix flakey integration test

---

deploy/charts/rig-operator/templates/deployment.yaml

🔧 Add pod annotation for rolling on config change

---

cmd/common/prompt.go
cmd/rig/cmd/capsule/root/setup.go
pkg/utils/users_helpers.go

- Show list of capsules when prompting for a capsule name
- Show validation error when typing ill-formatted password

CLI improvements

---

cmd/rig/cmd/base/auth.go
cmd/rig/cmd/capsule/mount/remove.go
cmd/rig/cmd/capsule/network/configure.go
cmd/rig/cmd/project/setup.go
cmd/rig/cmd/root.go
go.mod
go.sum

:sparkles: get license info method

:sparkles:  cli-license-info

---

pkg/manager/manager.go

:bug: Fix getEnvWithDefault returning wrong value

---

deploy/charts/rig-platform/Chart.yaml
deploy/charts/rig-platform/templates/_config.tpl
deploy/charts/rig-platform/templates/capsule.yaml
deploy/charts/rig-platform/templates/configmap.yaml
deploy/charts/rig-platform/values.yaml

- Put non-secret configuration in a ConfigMap
- Put secret configuration in a Secret
- Add missing default values
- Bump appVersion to v0.3.3 for configfile merge support

🔧 Revamp config in rig-platform chart

---

Makefile
docs/docs/operator-manual/crd-operator.mdx

- :memo: capsule spec versioning
- :memo: make docs & fix capsule spec

docs change

---

docs/crd-ref-docs/templates/gv_list.tpl
docs/docs/api/config/v1alpha1.md
docs/docs/api/v1alpha1.md
docs/docs/api/v1alpha2.md

:memo: Remove edit this page button from ref doc pages

---

deploy/charts/rig-operator/values.yaml
docs/docs/api/config/v1alpha1.md
pkg/api/config/v1alpha1/config_types.go

- fix typo in OperatorConfig godocs

:memo: Add documentation for rig-operator helm chart values

---

cmd/common/utils.go
cmd/rig/cmd/group/add_member.go
cmd/rig/cmd/group/get_groups_for_member.go
cmd/rig/cmd/group/get_members.go
cmd/rig/cmd/group/remove_member.go
cmd/rig/cmd/group/setup.go

- :bug: fixed cli-error
- :bug: memberID fixes

cli group fixes

---

proto/rig/api/v1/capsule/service.proto

- :sparkles: rollout msg on deploy

rollout msg on deploy

---

deploy/charts/rig-platform/templates/_config.tpl
deploy/charts/rig-platform/values.yaml
docs/docs/api/config/v1alpha1.md
pkg/api/config/v1alpha1/config_types.go
pkg/api/config/v1alpha1/zz_generated.deepcopy.go
pkg/controller/capsule_controller.go
proto/rig/api/v1/authentication/service.proto
proto/rig/model/auth.proto

- add oidc configuration in platform config
- make chart able to render oidc configuration
- add sso info in GetAuthConfig so that the frontend can conditionally
render different SSO login options

✨ Add config and apis for OIDC SSO 

---

deploy/charts/rig-platform/Chart.yaml
deploy/charts/rig-platform/templates/_config.tpl
docs/docs/api/config/v1alpha1.md
docs/docs/api/platform-api.md
pkg/api/config/v1alpha1/config_types.go
proto/rig/api/v1/authentication/service.proto
taskfile.yaml

- Add icon configuration for oidc providers
- Change GetAuthConfig response to include a field icon instead of
issuerUrl
- fix race condition in github action generation test: ensure proto is
generated before generating docs
- Update chart to support setting icon

Replace issuer url with icon

---

deploy/charts/rig-platform/Chart.yaml

- Bump version of rig-platform image to v0.5.11

🔖 chart: rig-platform v0.2.40

---

cmd/rig-operator/apichecker/apichecker.go
cmd/rig-operator/main.go
pkg/apichecker/apichecker.go

Add new command `rig-operator apicheck`. This command will test if
webhooks are ready and that the api server can reach them by dry-running
a Capsule creation.

:sparkles: Add `rig-operator apicheck`

---

cmd/rig-ops/cmd/migrate/migrate.go
cmd/rig/cmd/capsule/deploy/deploy.go
cmd/rig/cmd/capsule/image/common.go
cmd/rig/cmd/capsule/root/create.go
go.mod
go.sum

🎨 Images are added not created, CLI version

---

pkg/controller/deployment_step.go
pkg/controller/pipeline/capsule_request.go
pkg/controller/plugin/external_plugin.go
pkg/controller/plugin/server.go
plugins/env_mapping/main.go
proto/rig/operator/api/v1/plugin/service.proto

Also renamed GetCurrent -> GetExisting and MarkUsedResource -> MarkUsedObject
and added comments to CapsuleRequest.

:sparkles: Implement missing Delete and MarkUsedObject functions in the plugin server/client

---

cmd/rig-ops/cmd/base/register.go
cmd/rig-ops/cmd/migrate/current_resources.go
cmd/rig-ops/cmd/migrate/migrate.go
cmd/rig-ops/cmd/migrate/reporting.go
deploy/charts/rig-operator/values.yaml
pkg/controller/pipeline/capsule_request.go
pkg/handler/api/pipeline/handler.go
pkg/roclient/layered_reader.go
pkg/roclient/layered_reader_test.go
pkg/roclient/reader.go
plugins/env_mapping/main.go
plugins/env_mapping/types/types.go
proto/rig/operator/api/v1/pipeline/service.proto

layered reader, and general restructuring,

:sparkles: correctly migrated ingress

---

cmd/rig-ops/cmd/migrate/current_resources.go
cmd/rig-ops/cmd/migrate/migrate.go
cmd/rig-ops/cmd/migrate/reporting.go
cmd/rig-ops/cmd/migrate/setup.go

:bug: added k8sReader to read from files

---

docs/docs/getting-started/cli-install.md
docs/docs/operator-manual/ci-cd.mdx
docs/docs/operator-manual/ci-cd/github-actions.mdx
docs/docs/operator-manual/ci-cd/gitlab-pipelines.mdx
docs/docs/operator-manual/cli.mdx
docs/menu.js
docs/src/constants/versions.ts

- Add preface to ci-cd section about how to prepare CI/CD environment.
- Add gitlab instructions
- Remove v prefix in rig version, to be able to use it in image
versions.

📝 Revise CI/CD docs 

---

.github/workflows/main-docs.yml
build/package/docs.Dockerfile
build/package/docs.Dockerfile.dockerignore
taskfile.yaml

This adds build of docs to github actions and deploys it on the rig.dev
infra structure.

🚀 Build and deploy docs on rig.dev infra

---

cmd/common/prompt.go
cmd/common/useridentifier.go
cmd/rig/cmd/auth/login.go
cmd/rig/cmd/user/create.go
pkg/cli/module.go

This is in preparation of CLI unit tests

:recycle: Some refactoring of the prompting struct

---

cmd/rig/cmd/cmdconfig/config.go
cmd/rig/cmd/cmdconfig/context.go
pkg/cli/client.go
pkg/cli/module.go
pkg/cli/test_module.go

This is the last refactoring step before I'll add the CLI unit tests

:recycle: CLI config and module refactor

---

.mockery_uncommitted.yaml
cmd/rig/cmd/noop/setup.go
cmd/rig/cmd/root.go
cmd/rig/cmd/testing/some_test.go
taskfile.yaml

The unit tests are meant to test the setup of the Rig CLI where we
read in config, contexts, prompt for information and fetch
project/capsule/environment.
More tests to come.

:white_check_mark: Add testing framework + some tests for the CLI

---

cmd/rig-proto-gen/main.go
docs/docs/api/v1alpha2.md
pkg/api/platform/v1/types.go
pkg/api/v1alpha2/capsule_types.go

1. Name protobuf fields after json tags
2. Read protobuf index from protobuf tags to maintain protobuf
index consistency
3. Handle json-inlined fields such as to make json-proto conversion possible

:bug: Fixed a couple issues with rig-proto-gen

---

cmd/rig-operator/main.go
cmd/rig/cmd/capsule/instance/get.go
cmd/rig/cmd/capsule/instance/list.go
cmd/rig/cmd/capsule/instance/setup.go
cmd/rig/cmd/capsule/rollout/list.go
cmd/rig/cmd/capsule/rollout/setup.go
cmd/rig/cmd/capsule/root/setup.go
cmd/rig/cmd/capsule/root/status.go
cmd/rig/cmd/capsule/scale/get.go
cmd/rig/cmd/capsule/scale/vertical.go
go.mod
go.sum

- **:sparkles: Introduce verbose flag on capsule status cmd**

:sparkles: Add verbose flag to capsule status, and update capsule status according to api changes

---

cmd/rig-ops/cmd/base/register.go
pkg/api/platform/v1/conversion.go

:bug: Error message when no rig context in rig-ops migrate

---

cmd/rig/cmd/capsule/common.go
cmd/rig/cmd/capsule/deploy/deploy.go
cmd/rig/cmd/capsule/jobs/add.go
cmd/rig/cmd/capsule/root/promote.go
cmd/rig/cmd/capsule/root/setup.go
cmd/rig/cmd/capsule/root/status.go
cmd/rig/cmd/capsule/scale/horizontal.go
cmd/rig/cmd/capsule/scale/vertical.go
cmd/rig/cmd/dev/host.go
pkg/api/platform/v1/conversion.go
pkg/field/apply_test.go
pkg/field/compare.go
pkg/field/compare_test.go

We can consider renaming this cmd to something like copy or clone, when we get full promotion pipeline

✨ Add simple promotion v1

---

cmd/rig-proto-gen/main.go
cmd/rig/cmd/capsule/deploy/deploy.go
deploy/charts/rig-operator/templates/crd.yaml
docs/docs/api/platform-api.md
docs/docs/api/platformv1.md
docs/docs/api/v1alpha2.md
pkg/api/platform/v1/decode.go
pkg/api/platform/v1/types.go
pkg/api/platform/v1/zz_generated.deepcopy.go
pkg/api/v1alpha2/capsule_types.go
pkg/api/v1alpha2/zz_generated.deepcopy.go
proto/rig/platform/v1/generated.proto
scripts/crdcopy.py
taskfile.yaml

This required some fixing in the proto-gen script.
Also added a hacky crdcopy script to copy generated crd into
the helm charts.

:sparkles: Add Extensions to the capsule types

---

cmd/common/pipeline.go
cmd/rig/cmd/capsule/pipeline/progress.go
go.mod
go.sum
pkg/rbac/actions.go

- **:art: Redo triggers to more logical and include all or one condition**
- **:art: Implement redo pipeline trigger changes in the CLI**

:art: IMplement trigger changes in the cli

---

cmd/common/tview_yaml.go
cmd/rig-ops/cmd/migrate/reporting.go
cmd/rig/cmd/capsule/common.go
cmd/rig/cmd/capsule/dry_run.go
cmd/rig/cmd/capsule/pipeline/progress.go
pkg/obj/comparison.go
pkg/obj/decode.go

For each resource from the dry-run, show both the
new, the current and the diff (with toggles between
the three states).

:sparkles: Improve dry-run interactivity
